/*
 * generated by Nore (https://github.com/junjiemars/nore)
*/

/*
#include <nore.h>
*/
#include <stdio.h>

#define _unused_(x) ((void)(x))

int main(int argc, char **argv) {
    _unused_(argc);
    _unused_(argv);

    printf("Hello, Nore!\n");
    return 0;
}

